config/routes.rb
TravexV2::Application.routes.draw do

  Page.all.each do |page|
    get "#{page.anchor}" => 'application#page'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  get '/:country/hotels' => 'countries#hotels', as: 'hotels'
  get '/:country/visa' => 'countries#visa', as: 'visa'
  get '/:country/request' => 'countries#request_tour', as: 'request_tour'

  get '/:country' => 'countries#show', as: 'country'
  get '/:country/:city' => 'cities#show', as: 'city'
  get '/:country/:city/:hotel' => 'hotels#show', as: 'hotel'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/box.rb
class Box < ActiveRecord::Base
  attr_accessible :content, :name
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :country_id, :title, :anchor

  belongs_to :country, :class_name => "Country", :foreign_key => "country_id"
  has_many :hotels, :class_name => "Hotel", :foreign_key => "city_id"

end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :title, :anchor, :description, :image, :visa_information
  has_attached_file :image,
                    :storage => :dropbox,
                    :dropbox_credentials => Rails.root.join("#{Rails.root}/config/dropbox.yml"),
                    :dropbox_options => {:path => proc { |style| "countries/#{id}/#{style}/#{image.original_filename}" }}

  has_many :cities, :class_name => "City", :foreign_key => "country_id"
  has_many :hotels, :through => :cities

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  attr_accessible :city_id, :title, :anchor

  belongs_to :city, :class_name => "City", :foreign_key => "city_id"

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :anchor, :title, :sort
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :anchor, :content, :title, :header, :header4

  def train?
    return true if self.anchor == '/train'
    false
  end

  def visas?
    return true if self.anchor == '/visas'
    false
  end

  def avia?
    return true if self.anchor == '/avia'
    false
  end

  def root?
    return true if self.anchor == '/'
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protect_from_forgery except: :page
  before_filter :boxs

  def page
    @page = Page.find_by_anchor(request.fullpath)
  end

private

  def boxs
    @boxs = Box.all
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def show
    @city = City.find_by_anchor(params[:city])
    @country = @city.country
  end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  before_filter :find

  def show
  end

  def visa
  end

  def hotels
  end

  def request_tour
  end

private

  def find
    @country = Country.find_by_anchor(params[:country])
  end

end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController

  def show
    @hotel = Hotel.find_by_anchor(params[:hotel])
    @city = @hotel.city
    @country = @city.country
  end

end

app/controllers/mail_controller.rb
class MailController < ApplicationController

  def avia
    Mails.avia(params[:avia]).deliver
    render text: true
  end

  def hotel
    Mails.hotel(params[:hotel]).deliver
    render text: true
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def server
    'http://spec.gooddays.ru/.juicy/'
    #'http://travex-local-php/'
  end

  def hotel_mail_path
    "#{server}hotel.php"
  end

  def avia_mail_path
    "#{server}avia.php"
  end

  def train_mail_path
    "#{server}train.php"
  end

  def drop(file)
    url = URI.parse("https://dl.dropboxusercontent.com/u/4829990/")
    p = file.path
    p = p.match(/^Public\//).post_match
    url = "#{url}#{p}"
    url
  end

  def countries
    counrties = Country.all(order: 'title ASC')
    render partial: 'layouts/elems', locals: {elems: counrties}
  end

  def cities(country = nil)
    if country
      cities = country.cities
    else
      cities = City.all
    end
    
    render partial: 'layouts/elems', locals: {elems: cities}
  end

  def hotels(country = nil)
    if country
      hotels = country.hotels
    else
      hotels = Hotel.all
    end
    render partial: 'layouts/elems', locals: {elems: hotels}
  end

  def menu
    @menus = Menu.all(order: 'sort')
    render partial: 'layouts/menu'
  end

  def box(name)
    @boxs.each do |box|
      if box.name == name
        return raw(box.content)
      end
    end
  end

end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper

  def visas
    @visa_link = true
    countries = Country.where("visa_information <> ''")
    render partial: 'layouts/elems', locals: {elems: countries}
  end

end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/mail_helper.rb
module MailHelper
end

app/views/application/page.html.erb
<%= raw @page.content %>

<% if @page.train? %>
  <%= render partial: 'layouts/train' %>
<% end %>

<% if @page.avia? %>
  <%= render partial: 'layouts/avia' %>
<% end %>

<% if @page.root? %>
  <%= countries %>
<% end %>

<% if @page.visas? %>
  <%= visas %>
<% end %>

app/views/cities/show.html.erb
<%= hotels %>

app/views/countries/_country_menu.html.erb
<% content_for :menu do %>
  <ul>
      <li><%= link_to "Описание страны", country_path(@country.anchor), class: ("active" if params[:action] == 'show') %></li>
    <% if !@country.visa_information.blank? %>
      <li><%= link_to "Виза", visa_path(@country.anchor), class: ("active" if params[:action] == 'visa') %></li>
    <% end %>
    <% if @country.hotels.size > 0 %>
      <li><%= link_to "Отели", hotels_path(@country.anchor), class: ("active" if params[:action] == 'hotels') %></li>
    <% end %>
      <li><%= link_to "Заявка на подбор тура", request_tour_path(@country.anchor), class: ("active" if params[:action] == 'request_tour') %></li>
  </ul>
<% end %>

app/views/countries/hotels.html.erb
<%= render 'country_menu' %>

<% if @country.cities.size > 0 %>
  <h3>Отели:</h3>
  <%= hotels(@country) %>
  <hr />
<% end %>

app/views/countries/request_tour.html.erb
<%= render 'country_menu' %>

app/views/countries/show.html.erb
<%= render 'country_menu' %>

<% if @country.cities.size > 0 %>
  <h3>Города:</h3>
  <%= cities(@country) %>
  <hr />
<% end %>

<% unless @country.description.blank? %>
  <%= raw @country.description %>
<% end %>

app/views/countries/visa.html.erb
<%= render 'country_menu' %>

<% unless @country.visa_information.blank? %>
  <%= raw @country.visa_information %>
<% end %>

app/views/hotels/_form.html.erb
<%= form_tag(hotel_mail_path, {id: 'hotel', class: "form hotel"}) do %>
  <fieldset>
    <legend>Бронирование отеля</legend>
    <input type="hidden" name="hotel[country]" value="<%= @country.title %>">
    <input type="hidden" name="hotel[city]" value="<%= @city.title %>">
    <input type="hidden" name="hotel[hotel]" value="<%= @hotel.title %>">
    <div class="field">
      <label>Дата заезда: *</label>
      <div class="input"><input class="date_i" name="hotel[in_date]" type="text" required></div>
    </div>
    <div class="field">
      <label>Дата выезда: *</label>
      <div class="input"><input class="date_i" name="hotel[out_date]" type="text" required></div>
    </div>
    <div class="field">
      <label>Ориентировочная стоимость за номер:</label>
      <div class="input"><input name="hotel[price]" type="text"></div>
    </div>
    <div class="field">
      <label>Дополнительные пожелания:</label>
      <div class="input"><textarea name="hotel[comment]"></textarea></div>
    </div>
    <div class="field">
      <label>Тип номера: *</label>
      <div class="input">
        <select required name="hotel[type]">
          <option value="0">Одноместный</option>
          <option value="1">Двуместный</option>
        </select>
      </div>
    </div>
    <div class="field">
      <label>Кол-во номеров: *</label>
      <div class="input">
        <select required name="hotel[count]">
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
        </select>
      </div>
    </div>
    <div class="field">
      <label>Форма оплаты: *</label>
      <div class="input">
        <select required name="hotel[byu]">
          <option value="0">наличная</option>
          <option value="1">безналичная</option>
          <option value="2">кредитная карта</option>
        </select>
      </div>
    </div>
    <div class="label center">Заказчик</div>
    <div class="field">
      <label>Контактное лицо: *</label>
      <div class="input"><input required name="hotel[contact]" type="text"></div>
    </div>
    <div class="field">
      <label>Телефон: *</label>
      <div class="input"><input required name="hotel[phone]" type="text"></div>
    </div>
    <div class="field">
      <label>Факс</label>
      <div class="input"><input name="hotel[fax]" type="text"></div>
    </div>
    <div class="field">
      <label>E-mail</label>
      <div class="input"><input name="hotel[email]" type="text"></div>
    </div>
    <div class="field btns">
      <input type="submit" value="Отправить">
      <input type="reset" value="Сброс формы">
    </div>
  </fieldset>
<% end %>

app/views/hotels/show.html.erb
<%#= debug @hotel %>
<%= render 'form' %>

app/views/layouts/_avia.html.erb
<%= form_tag(avia_mail_path, {id: 'avia', class: "form"}) do %>
  <fieldset>
    <legend>Заказчик</legend>
    <div class="field">
      <label>Имя/Наименование:</label>
      <div class="input"><input type="text" name="avia[name]" required></div>
    </div>
    <div class="field">
      <label>Контактный телефон:</label>
      <div class="input"><input type="text" name="avia[phone]" required></div>
    </div>
    <div class="field">
      <label>Факс:</label>
      <div class="input"><input type="text" name="avia[fax]"></div>
    </div>
    <div class="field">
      <label>E-mail:</label>
      <div class="input"><input type="email" name="avia[email]"></div>
    </div>
  </fieldset>
  <fieldset>
    <legend>Билеты</legend>
    <div class="label">Данные о пассажирах</div>
    <table class="bilets">
      <tr>
        <th class="fio">Фамилия, Имя, отчество</th>
        <th class="category">Категория</th>
      </tr>
      <tr>
        <td class="fio"><input type="text" name="avia[passager][0][fio]" required></td>
        <td>
          <select name="avia[passager][0][years]">
            <option value="0">"Взрослый"(&gt;25 лет)</option>
            <option value="1">"Молодежный"(12-25 лет)</option>
            <option value="2">"Ребенок"(2-12 лет)</option>
            <option value="3">"Младенец"(0-2 лет)</option>
          </select>
        </td>
      </tr>
      <tr class="after_pass">
        <td class="btn" colspan="2"><input class="add_passager" type="button" value="Добавить пассажира" /></td>
      </tr>
    </table>
    <div class="label">Даты и пункты отлета и прилета</div>
    <table>
      <tr>
        <td class="field">
          <label for="">Дата вылета:</label>
          <div class="input"><input class="date_i" type="text" name="avia[out_date]" required></div>
        </td>
        <td class="field">
          <label for="">Пункт вылета:</label>
          <div class="input"><input type="text" name="avia[out_point]" required></div>
        </td>
      </tr>
      <tr>
        <td class="field">
          <label for="">Дата прилета:</label>
          <div class="input"><input class="date_i" type="text" name="avia[in_date]" required></div>
        </td>
        <td class="field">
          <label for="">Пункт прилета:</label>
          <div class="input"><input type="text" name="avia[in_point]" required></div>
        </td>
      </tr>
    </table>
    <div class="field">
      <label>Маршрут:</label>
      <div class="input"><textarea name="avia[route]"></textarea></div>
    </div>
    <div class="field">
      <label>Авиакомпания:</label>
      <div class="input"><input type="text" name="avia[company]"></div>
    </div>
    <div class="label">Дополнительная информация</div>
    <table class="radio">
      <tr>
        <td>Вылет:</td>
        <td>
          <label><input name="avia[out_time]" checked value="0" type="radio">Утро</label>
          <label><input name="avia[out_time]" value="1" type="radio">День</label>
          <label><input name="avia[out_time]" value="2" type="radio">Вечер</label>
        </td>
      </tr>
      <tr>
        <td>Класс:</td>
        <td>
          <label><input name="avia[class_type]" checked value="0" type="radio">Экономический</label>
          <label><input name="avia[class_type]" value="1" type="radio">Бизнес</label>
          <label><input name="avia[class_type]" value="2" type="radio">Первый</label>
        </td>
      </tr>
      <tr>
        <td>Форма оплаты:</td>
        <td>
          <label><input name="avia[payment]" checked value="0" type="radio">Наличный расчет</label>
          <label><input name="avia[payment]" value="1" type="radio">Безналичный расчет 	</label>
          <label><input name="avia[payment]" value="2" type="radio">Кредитная карта</label>
        </td>
      </tr>
    </table>
    <div class="field">
      <label>Примечания:</label>
      <div class="input"><textarea name="avia[note]"></textarea></div>
    </div>
    <div class="field btns">
      <input type="submit" value="Отправить">
      <input type="reset" value="Сброс формы">
    </div>
  </fieldset>
<% end -%>

app/views/layouts/_elems.html.erb
<% elems ||= false %>

<% if elems %>
  <% elem_class = elems.first.class.name %>
  <div class="cols cols4 ul_with_flags">
    <% elems.in_groups(4, false) do |group| %>
      <ul class="col">
        <% group.each do |elem| %>
          <% if elem %>
            <% case elem_class %>
              <% when "Country" %>
              <% if @visa_link %>
              <li>
                <%= image_tag drop(elem.image) if elem.image_file_size %>
                <a href="<%= visa_path(elem.anchor) %>"><%= elem.title %></a>
              </li>
              <% else %>
              <li>
                <%= image_tag drop(elem.image) if elem.image_file_size %>
                <a href="<%= country_path(elem.anchor) %>"><%= elem.title %></a>
              </li>
              <% end %>
              <% when "City" %>
              <li><a href="<%= city_path(elem.country.anchor, elem.anchor) %>"><%= elem.title %></a></li>
              <% when "Hotel" %>
              <li><a href="<%= hotel_path(elem.city.country.anchor, elem.city.anchor, elem.anchor) %>"><%= elem.title %></a></li>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    <% end %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<% header = @page.header if @page %>
<% header4 = @page.header4 if @page %>

<% header = 'countries' if @country %>
<% header4 = true if @country %>

<% header = 'countries' if @city %>
<% header4 = true if @city %>

<% header = 'hotels' if @hotel %>
<% header4 = true if @hotel %>

<header>

  <a href="/"><img src="/assets/headers/index/1x1.jpg"></a>
  <img src="/assets/headers/index/1x2.jpg">
  <img src="/assets/headers/<%= header %>/1x3.jpg">

  <div class="menu">
    <a href="/" class="logo"><img src="/assets/logo.png" alt="" /></a>
    <%= menu %>
  </div>
  <img src="/assets/headers/<%= header %>/2x2.jpg">
  <img src="/assets/headers/<%= header %>/2x3.jpg">

  <img src="/assets/headers/index/3x1.gif">
  <img src="/assets/headers/<%= header %>/3x2.jpg">
  <img src="/assets/headers/<%= header %>/3x3.jpg">
  <% if header4 == "true" %>
    <%# line 4: contacts country hotel %>
    <img class="image_right" src="/assets/headers/<%= header %>/4x3.jpg">
  <% end %>

</header>

app/views/layouts/_makeup.html.erb
<img class="image_left" src="http://travex1/images/ya_acacia1.jpg">
<p><u>ООО "ТРАВЭКС" свидетельствует Вам свое почтение и предлагает Вашему вниманию более подробную информацию о нашей компании.</u></p>
<p><strong>ООО "ТРАВЭКС" свидетельствует Вам свое почтение и предлагает Вашему вниманию более подробную информацию о нашей компании.</strong></p>
<p><a href="">ООО "ТРАВЭКС" свидетельствует Вам свое почтение и предлагает Вашему вниманию более подробную информацию о нашей компании.</a></p>
<p><i>ООО "ТРАВЭКС" свидетельствует Вам свое почтение и предлагает Вашему вниманию более подробную информацию о нашей компании.</i></p>
<h1>Заголовок 1</h1>
<h1 class="bg">Заголовок 1</h1>
<h2>Заголовок 2</h2>
<h2 class="bg">Заголовок 2</h2>
<h3>Заголовок 3</h3>
<h3 class="bg">Заголовок 3</h3>
<h4>Заголовок 4</h4>
<h4 class="bg">Заголовок 4</h4>
<h5>Заголовок 5</h5>
<h5 class="bg">Заголовок 5</h5>
<h6>Заголовок 6</h6>
<h6 class="bg">Заголовок 6</h6><p><small>ООО "ТРАВЭКС" свидетельствует Вам свое почтение и предлагает Вашему вниманию более подробную информацию о нашей компании.</small></p>
<p><big>ООО "ТРАВЭКС" свидетельствует Вам свое почтение и предлагает Вашему вниманию более подробную информацию о нашей компании.</big></p>
<hr>
<p class="left">ООО "ТРАВЭКС" свидетельствует Вам свое почтение и предлагает.</p>
<p class="right">ООО "ТРАВЭКС" свидетельствует Вам свое почтение и предлагает.</p>
<p class="center">ООО "ТРАВЭКС" свидетельствует Вам свое почтение и предлагает.</p>
<img class="image_right" src="http://travex1/images/ya_acacia1.jpg">
<ul>
  <li>ООО "ТРАВЭКС" свидетельствует Вам свое почтение и предлагает.</li>
  <li>ООО "ТРАВЭКС" свидетельствует Вам свое почтение и предлагает.</li>
  <li>ООО "ТРАВЭКС" свидетельствует Вам свое почтение и предлагает.</li>
</ul>
<ol>
  <li>ООО "ТРАВЭКС" свидетельствует Вам свое почтение и предлагает.</li>
  <li>ООО "ТРАВЭКС" свидетельствует Вам свое почтение и предлагает.</li>
  <li>ООО "ТРАВЭКС" свидетельствует Вам свое почтение и предлагает.</li>
</ol>
<ul class="no_li">
  <li><strong>ООО "ТРАВЭКС"</strong> свидетельствует Вам свое почтение и предлагает.</li>
  <li><strong>ООО "ТРАВЭКС"</strong> свидетельствует Вам свое почтение и предлагает.</li>
  <li><strong>ООО "ТРАВЭКС"</strong> свидетельствует Вам свое почтение и предлагает.</li>
  <li><strong>ООО "ТРАВЭКС"</strong> свидетельствует Вам свое почтение и предлагает.</li>
</ul>
<div class="cols cols2">
  <div class="col">
    <p>ООО "ТРАВЭКС" свидетельствует Вам свое почтение и предлагает Вашему вниманию более подробную информацию о нашей компании.</p>
    <p>Основным направлением деятельности ООО "ТРАВЭКС" является организация деловых поездок для наших корпоративных клиентов и предоставление туристических услуг высшего качества.</p>
  </div>
  <div class="col">
    <p>ООО "ТРАВЭКС" свидетельствует Вам свое почтение и предлагает Вашему вниманию более подробную информацию о нашей компании.</p>
    <p>Основным направлением деятельности ООО "ТРАВЭКС" является организация деловых поездок для наших корпоративных клиентов и предоставление туристических услуг высшего качества.</p>
  </div>
</div>
<div class="cols cols3">
  <div class="col">
    <p>ООО "ТРАВЭКС" свидетельствует Вам свое почтение и предлагает Вашему вниманию более подробную информацию о нашей компании.</p>
    <p>Основным направлением деятельности ООО "ТРАВЭКС" является организация деловых поездок для наших корпоративных клиентов и предоставление туристических услуг высшего качества.</p>
  </div>
  <div class="col">
    <p>ООО "ТРАВЭКС" свидетельствует Вам свое почтение и предлагает Вашему вниманию более подробную информацию о нашей компании.</p>
    <p>Основным направлением деятельности ООО "ТРАВЭКС" является организация деловых поездок для наших корпоративных клиентов и предоставление туристических услуг высшего качества.</p>
  </div>
  <div class="col">
    <p>ООО "ТРАВЭКС" свидетельствует Вам свое почтение и предлагает Вашему вниманию более подробную информацию о нашей компании.</p>
    <p>Основным направлением деятельности ООО "ТРАВЭКС" является организация деловых поездок для наших корпоративных клиентов и предоставление туристических услуг высшего качества.</p>
  </div>
</div>
<div class="cols cols4">
  <div class="col">
    <p>Основным направлением деятельности ООО "ТРАВЭКС" является организация деловых поездок для наших корпоративных клиентов и предоставление туристических услуг высшего качества.</p>
  </div>
  <div class="col">
    <p>Основным направлением деятельности ООО "ТРАВЭКС" является организация деловых поездок для наших корпоративных клиентов и предоставление туристических услуг высшего качества.</p>
  </div>
  <div class="col">
    <p>Основным направлением деятельности ООО "ТРАВЭКС" является организация деловых поездок для наших корпоративных клиентов и предоставление туристических услуг высшего качества.</p>
  </div>
  <div class="col">
    <p>Основным направлением деятельности ООО "ТРАВЭКС" является организация деловых поездок для наших корпоративных клиентов и предоставление туристических услуг высшего качества.</p>
  </div>
</div>
<div class="cols cols4 ul_with_flags">
  <ul class="col">
    <li><img src="i/flags/fl_ger.gif" alt="" /><a href="">Германия</a></li>
    <li><img src="i/flags/fl_ger.gif" alt="" /><a href="">Германия</a></li>
    <li><img src="i/flags/fl_ger.gif" alt="" /><a href="">Германия</a></li>
  </ul>
  <ul class="col">
    <li><img src="i/flags/fl_ger.gif" alt="" /><a href="">Германия</a></li>
    <li><img src="i/flags/fl_ger.gif" alt="" /><a href="">Германия</a></li>
    <li><img src="i/flags/fl_ger.gif" alt="" /><a href="">Германия</a></li>
  </ul>
  <ul class="col">
    <li><img src="i/flags/fl_ger.gif" alt="" /><a href="">Германия</a></li>
    <li><img src="i/flags/fl_ger.gif" alt="" /><a href="">Германия</a></li>
    <li><img src="i/flags/fl_ger.gif" alt="" /><a href="">Германия</a></li>
  </ul>
  <ul class="col">
    <li><img src="i/flags/fl_ger.gif" alt="" /><a href="">Германия</a></li>
    <li><img src="i/flags/fl_ger.gif" alt="" /><a href="">Германия</a></li>
    <li><img src="i/flags/fl_ger.gif" alt="" /><a href="">Германия</a></li>
  </ul>
</div>

app/views/layouts/_menu.html.erb
<ul>
  <% @menus.each do |menu| %>
    <li><a class="<%= 'active' if request.fullpath[menu.anchor] != nil %>" href="<%= menu.anchor %>"><%= menu.title %></a></li>
  <% end %>
</ul>

app/views/layouts/_nav.html.erb
<% h1 = '' %>
<% h1 = @page.title if @page && @page.anchor != '/' %>
<% h1 = @country.title if @country %>
<% h1 = "#{@country.title} - #{@city.title}" if @city %>
<% h1 = "#{@country.title} - #{@city.title} - #{@hotel.title}" if @hotel %>

<nav>
  <h1><%= h1 %></h1>
  <%= yield :menu %>
</nav>

app/views/layouts/_train.html.erb
<%= form_tag(train_mail_path, {id: 'train', class: "form"}) do %>
  <fieldset>
    <legend>Заказчик</legend>
    <div class="field">
      <label>Имя/Наименование:</label>
      <div class="input"><input type="text" name="train[name]" required></div>
    </div>
    <div class="field">
      <label>Контактный телефон:</label>
      <div class="input"><input type="text" name="train[phone]" required></div>
    </div>
    <div class="field">
      <label>E-mail:</label>
      <div class="input"><input type="email" name="train[email]"></div>
    </div>
  </fieldset>
  <fieldset>
    <legend>Билеты</legend>
    <div class="label">Данные о пассажирах</div>
    <table class="bilets">
      <tr>
        <th class="fio">Фамилия, Имя, отчество</th>
        <th class="category">Дата рождения</th>
      </tr>
      <tr>
        <td class="fio"><input type="text" name="train[passager][0][fio]" required></td>
        <td>
          <input type="text" name="train[passager][0][birth]" required>
        </td>
      </tr>
      <tr class="after_pass">
        <td class="btn" colspan="2"><input class="add_passager" type="button" value="Добавить пассажира" /></td>
      </tr>
    </table>
    <div class="label">Даты и пункты отправления и прибытия</div>
    <table>
      <tr>
        <td class="field">
          <label for="">Дата отправления:</label>
          <div class="input"><input class="date_i" type="text" name="train[out_date]" required></div>
        </td>
        <td class="field">
          <label for="">Город отправления:</label>
          <div class="input"><input type="text" name="train[out_point]" required></div>
        </td>
      </tr>
      <tr>
        <td class="field">
          <label for="">Дата прибытия:</label>
          <div class="input"><input class="date_i" type="text" name="train[in_date]" required></div>
        </td>
        <td class="field">
          <label for="">Город прибытия:</label>
          <div class="input"><input type="text" name="train[in_point]" required></div>
        </td>
      </tr>
    </table>
    <div class="field">
      <label>Маршрут:</label>
      <div class="input"><textarea name="train[route]"></textarea></div>
    </div>
    <div class="label">Дополнительная информация</div>
    <table class="radio">
      <tr>
        <td>Вылет:</td>
        <td>
          <label><input name="train[out_time]" checked value="0" type="radio">Утро</label>
          <label><input name="train[out_time]" value="1" type="radio">День</label>
          <label><input name="train[out_time]" value="2" type="radio">Вечер</label>
        </td>
      </tr>
      <tr>
        <td>Класс:</td>
        <td>
          <label><input name="train[class_type]" checked value="0" type="radio">Экономический</label>
          <label><input name="train[class_type]" value="1" type="radio">Бизнес</label>
          <label><input name="train[class_type]" value="2" type="radio">Первый</label>
        </td>
      </tr>
      <tr>
        <td>Форма оплаты:</td>
        <td>
          <label><input name="train[payment]" checked value="0" type="radio">Наличный расчет</label>
          <label><input name="train[payment]" value="1" type="radio">Безналичный расчет 	</label>
          <label><input name="train[payment]" value="2" type="radio">Кредитная карта</label>
        </td>
      </tr>
    </table>
    <div class="field">
      <label>Примечания:</label>
      <div class="input"><textarea name="train[note]"></textarea></div>
    </div>
    <div class="field btns">
      <input type="submit" value="Отправить">
      <input type="reset" value="Сброс формы">
    </div>
  </fieldset>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
  <title></title>
  <meta name="description">
  <meta content="width=device-width" name="viewport">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="wrapper">

    <%= render partial: 'layouts/header' %>

    <section>

      <%= render partial: 'layouts/nav' %>

      <%= yield %>
    </section>

    <footer>
      <%= box('footer') %>
    </footer>

  </div>

</body>
</html>